upgrade to commons-digester3
jenkinsci/emma-plugin pull request #11
Opened 2021-04-30 18:34 UTC by car-roll

Upgrade to commons-digester3. downstream of https://github.com/jenkinsci/jenkins/pull/5320

ping @daniel-beck 

- [x] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your master branch!
- [x] Ensure that the pull request title represents the desired changelog entry
- [x] Please describe what you did
- [ ] Link to relevant issues in GitHub or Jira
- [x] Link to relevant pull requests, esp. upstream and downstream changes
- [ ] Ensure you have provided tests - that demonstrates feature works or fixes the issue

2021-04-30 21:18 UTC, marek-parfianowicz requested changes
In a similar change in the Clover plugin (see https://github.com/jenkinsci/clover-plugin/pull/24), the following snippet was added:

`digester.setXIncludeAware(false);
            try {
                digester.setFeature("http://apache.org/xml/features/disallow-doctype-decl", true);
                digester.setFeature("http://xml.org/sax/features/external-general-entities", false);
                digester.setFeature("http://xml.org/sax/features/external-parameter-entities", false);
                digester.setFeature("http://apache.org/xml/features/nonvalidating/load-external-dtd", false);
            } catch (ParserConfigurationException ex) {
                throw new SAXException("Failed to securely configure xml digester parser", ex);
            }`

I do not see such fragment in this PR for the emma plugin.

2021-05-01 01:16 UTC, car-roll commented
@marek-parfianowicz you're right, that section of code has been added

2021-05-01 06:02 UTC, marek-parfianowicz approved these changes
Looks great! 👍

2021-05-01 23:59 UTC, olamy approved these changes

2021-05-03 10:20 UTC, alecharp approved these changes

2021-05-03 14:18 UTC, MRamonLeon approved these changes

2021-05-03 15:33 UTC, rsandell approved these changes

2021-06-01 09:08 UTC, merged